### ISSUE TITLE
Timing Issue in Vue lifecycle?

### ISSUE THREAD

**Issue by CAJazzer** [ManuelSch/vuex-rxjs#1]
Trying to do asynchronous operation (Action) when component loads ( mounted() ).  State does not get properly updated.  Using the counter example code:
```javascript
// Does not work
public mounted() {
 store.increment();
}

// Works
public mounted() {
  setTimeout(() => {
    store.increment();
  }, 1);
}
```

**Comment by ManuelSch** [comment]
Thanks for the report. I'll take a look at the issue and let you know asap.
